<?php 
// password reset system
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

require '../PHPMailer/src/Exception.php';
require '../PHPMailer/src/PHPMailer.php';
require '../PHPMailer/src/SMTP.php';
require '../classes/DB.php';
require 'functions.inc.php';

if (isset($_POST['reset-request-submit'])) {

    try {
        $selector = bin2hex(random_bytes(8)); 
        $token = random_bytes(32);

        $url = "localhost:8888/PHP_eindproject/create-new-password.php?selector=" . $selector . "&validator=" . bin2hex($token);

        $expires = date("U") + 1800;


        $conn = DB::getConnection();

        $userEmail = $_POST['email'];

        $statement = $conn->prepare("DELETE FROM pwdreset WHERE pwdResetEmail=:email");
        $statement->bindValue(":email", $userEmail);
        $statement->execute();

        $options = [
            'cost' => 12,
        ];
        $tokenHash = password_hash($token, PASSWORD_DEFAULT, $options);

        $statementTwo = $conn->prepare("INSERT INTO pwdreset (pwdResetEmail, pwdResetSelector, pwdResetToken, pwdResetExpires) VALUES (:email, :selector, :token, :expires)");
        $statementTwo->bindValue(":email", $userEmail);
        $statementTwo->bindValue(":selector", $selector);
        $statementTwo->bindValue(":token", $tokenHash);
        $statementTwo->bindValue(":expires", $expires);
        $statementTwo->execute();
    // ^^ token system --- maakt tokens om te binden aan password reset requests^^
    //
    //below is mail system
        $mail = new PHPMailer();    
        $mail->isSMTP();
        $mail->SMTPDebug = 2;
        $mail->SMTPOptions = array(
            'ssl' => array(
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
            )
            );
        $config = Config::getConfig();
        $user = $config['mailuser'];
        $password = $config['mailpw'];

        $mail->Host = 'smtp.gmail.com';
        $mail->SMTPAuth = true;
        $mail->Username = $user; //paste one generated by Mailtrap
        $mail->Password = $password; //paste one generated by Mailtrap
        $mail->SMTPSecure = 'tls';
        $mail->Port = 587;
        $mail->setFrom('IMDmediaHelpdesk@gmail.com', 'IMDmediaHelpdesk');
        $mail->addAddress($userEmail);
        $mail->isHTML(true);
        $mail->Subject = 'Test Email via Mailtrap SMTP using PHPMailer';
        $mail->Body = '<p>Here is your reset link: </br><a href=' . $url . '>' . $url . '</a></p>';
        if(!$mail->send()){
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
        }else{
            echo 'Message has been sent';
        
       
        
        header("Location: ../reset-password.php?reset=success");

        }}
    catch (\Throwable $th){
        echo "something went wrong";
    }
}
else {
    header("Location: login.php");
}

//$subject = 'Reset your password for imdbehance';

//$message = '<p>We recieved a password reset request. The link to reset your password is below.
//If you did not make this request, you can ignore this email</p^>';
//$message .= '<p>Here is your password reset link: </br>';
//$message .= '<a href="' . $url . '">' . $url . '</a></p>';

//$headers = "From : IMDBehance <IMD_Eindproject@outlook.com>\r\n";
//$headers .= "Reply-To: IMD_Eindproject@outlook.com\r\n";
//$headers .= "Content-type: text/html\r\n";

//mail($to, $subject, $message, $headers);